# Site settings
title: Yingnan Song's Github Pages
email: syngod12345@gmail.com
description: >
 Guess what?
baseurl: ""
url: "http://yingnansong.github.io"
twitter_username: yingnansong
github_username:  yingnansong

# Build settings
markdown: kramdown
